import type { ColumnMapping, ImportType } from "../types"
import { IMPORT_FIELD_CONFIGS } from "../constants"
import { normalizeText } from "./parser"

const COLUMN_SYNONYMS: Record<string, string[]> = {
  sku: ["sku", "codigo", "code", "item", "cod"],
  nome: ["nome", "name"],
  sigla: ["sigla", "abreviacao", "abbr"],
  descricao: ["descricao", "description", "desc"],
  preco: ["preco", "price", "valor"],
  ativo: ["ativo", "active", "habilitado", "enabled"],
  diametro_mm: ["diametro", "diameter", "dia"],
  comprimento_mm: ["comprimento", "length", "compr", "comp"],
  comprimento: ["comprimento", "length", "compr", "comp"],
  material: ["material"],
  tipo: ["tipo", "type"],
  categoria_nome: ["categoria", "category", "cat"],
  conexao_nome: ["conexao", "connection", "conn"],
  conexao_sigla: ["sigla conexao", "conexao sigla"],
  familia_nome: ["familia", "family"],
  familia_cor: ["cor familia", "familia cor", "cor identificacao"],
  linha_nome: ["linha", "line"],
  osso_soft_nome: ["osso soft", "protocolo soft"],
  osso_hard_nome: ["osso hard", "protocolo hard"],
  rosca_interna: ["rosca", "thread"],
  regiao_apical: ["regiao apical", "apical"],
  regiao_cervical: ["regiao cervical", "cervical"],
  torque_insercao: ["torque insercao", "torque"],
  macrogeometria: ["macrogeometria"],
  superficie: ["superficie", "surface"],
  tipo_abutment_nome: ["tipo abutment", "abutment type"],
  tipo_componente_nome: ["tipo componente", "component type"],
  tipo_parafuso_nome: ["tipo parafuso", "screw type"],
  tipo_chave_nome: ["tipo chave", "key type"],
  tipo_fresa_nome: ["tipo fresa", "drill type"],
  tipo_complementar_nome: ["tipo complementar"],
  tipo_opcional_nome: ["tipo opcional"],
  tipo_kit_nome: ["tipo kit", "kit type"],
  parafuso_sku: ["sku parafuso", "parafuso sku"],
  chave_sku: ["sku chave", "chave sku"],
  implante_sku: ["sku implante", "implante sku"],
  diametro_plataforma_mm: ["diametro plataforma", "plataforma"],
  altura_transmucoso_mm: ["altura transmucoso", "transmucoso"],
  altura_corpo_mm: ["altura corpo", "corpo"],
  angulacao_graus: ["angulacao", "angulation", "angulo"],
  torque_ncm: ["torque ncm", "torque"],
  tipo_osso: ["tipo osso", "sigla tipo de osso", "bone type"],
  categoria: ["categoria hard soft", "hard soft"],
  diametro_mm_aplicavel: ["diametro aplicavel", "diametro mm aplicavel"],
  chaves_skus: ["chaves", "skus chaves"],
  fresas_skus: ["fresas", "skus fresas"],
  complementares_skus: ["complementares", "skus complementares"],
  opcionais_skus: ["opcionais", "skus opcionais"],
  implantes_skus: ["implantes", "skus implantes"],
  tipo_workflow_nome: ["tipo workflow", "workflow type"],
  ordem: ["ordem", "order"],
  expira_em: ["expira em", "expiracao", "validade"],
  itens: ["itens", "items"],
}

export function autoDetectMappings(
  fileHeaders: string[],
  importType: ImportType
): ColumnMapping[] {
  const fieldConfig = IMPORT_FIELD_CONFIGS[importType]
  if (!fieldConfig) return []

  return fieldConfig.targetFields.map((target) => {
    let matchedSource = fileHeaders.find((h) => normalizeText(h) === normalizeText(target.key))

    if (!matchedSource) {
      matchedSource = fileHeaders.find((h) => normalizeText(h) === normalizeText(target.label))
    }

    if (!matchedSource) {
      const synonyms = COLUMN_SYNONYMS[target.key] ?? []
      matchedSource = fileHeaders.find((h) => {
        const hNorm = normalizeText(h)
        return synonyms.some((s) => hNorm.includes(normalizeText(s)))
      })
    }

    return {
      sourceColumn: matchedSource ?? "",
      targetField: target.key,
      transform: target.transform as ColumnMapping["transform"],
      isRequired: target.required,
      isAutoGenerated: false,
    }
  })
}

export function applyMapping(
  rawRows: Record<string, unknown>[],
  mappings: ColumnMapping[]
): Record<string, unknown>[] {
  return rawRows.map((row) => {
    const mapped: Record<string, unknown> = {}

    for (const m of mappings) {
      if (m.isAutoGenerated) continue
      const rawValue = m.sourceColumn ? row[m.sourceColumn] : null
      mapped[m.targetField] = transformValue(rawValue, m.transform)
    }

    return mapped
  })
}

function transformValue(value: unknown, transform?: ColumnMapping["transform"]): unknown {
  if (value === null || value === undefined || value === "") return null
  if (!transform) return value

  switch (transform.type) {
    case "number": {
      const n = Number(String(value).replace(",", "."))
      return isNaN(n) ? null : n
    }
    case "boolean": {
      const s = String(value).toLowerCase()
      return ["true", "sim", "1", "yes", "s"].includes(s)
    }
    case "date":
      return value
    case "enum": {
      const normalized = String(value).trim().toLowerCase()
      return transform.values?.find((v) => v.toLowerCase() === normalized) ?? null
    }
    default:
      return value
  }
}

export function getTransformPreview(
  value: unknown,
  transform?: ColumnMapping["transform"]
): string {
  if (value === null || value === undefined || value === "") return "—"
  const transformed = transformValue(value, transform)
  if (transformed === null) return "(inválido)"
  return String(transformed)
}
