// ============ ENUMS & CONSTANTS ============

export type ImportType =
  | "hierarquia"
  | "implantes"
  | "abutments"
  | "componentes"
  | "parafusos"
  | "cicatrizadores"
  | "chaves"
  | "fresas"
  | "complementares"
  | "opcionais"
  | "kits"
  | "tipos_osso"
  | "protocolos_fresagem"
  | "tipos_workflow"
  | "etapas_workflow"
  | "promocionais"

export type RowSeverity = "error" | "warning" | "info"

// ============ FILE PARSING ============

export interface ParsedFile {
  fileName: string
  fileSize: number
  sheets: ParsedSheet[]
}

export interface ParsedSheet {
  name: string
  headers: string[]
  rows: RawRow[]
  totalRows: number
}

export interface RawRow {
  [columnHeader: string]: string | number | boolean | null
}

// ============ COLUMN MAPPING ============

export interface ColumnMapping {
  sourceColumn: string
  targetField: string
  transform?: ValueTransform
  isRequired: boolean
  isAutoGenerated?: boolean
}

export type ValueTransform =
  | { type: "number" }
  | { type: "boolean" }
  | { type: "date" }
  | { type: "enum"; values: string[] }
  | { type: "list" }

export interface MappingTemplate {
  id: string
  name: string
  importType: ImportType
  mappings: ColumnMapping[]
  createdAt: string
}

// ============ VALIDATION ============

export interface RowValidation {
  rowIndex: number
  severity: RowSeverity
  field: string
  message: string
  suggestion?: string
  value?: unknown
}

export interface ValidationResult {
  validRows: ValidatedRow[]
  errorRows: ValidatedRow[]
  warnings: RowValidation[]
  errors: RowValidation[]
  summary: ValidationSummary
}

export interface ValidatedRow {
  rowIndex: number
  data: Record<string, unknown>
  validations: RowValidation[]
  isValid: boolean
  isEditable: boolean
}

export interface ValidationSummary {
  totalRows: number
  validRows: number
  rowsWithWarnings: number
  rowsWithErrors: number
  errorsByField: Record<string, number>
  warningsByField: Record<string, number>
}

// ============ IMPORT EXECUTION ============

export type ImportStatus = "idle" | "parsing" | "mapping" | "validating" | "executing" | "completed" | "failed"

export interface ImportProgress {
  status: ImportStatus
  currentStep: number
  totalSteps: number
  currentBatch: number
  totalBatches: number
  processedRows: number
  totalRows: number
  insertedCount: number
  updatedCount: number
  skippedCount: number
  errorCount: number
  errors: ImportError[]
  startTime: number
  estimatedTimeRemaining?: number
  currentEntityLabel?: string
}

export interface ImportError {
  rowIndex: number
  data: Record<string, unknown>
  error: string
  errorCode: string
  recoverable: boolean
}

export interface ImportResult {
  success: boolean
  inserted: number
  updated: number
  skipped: number
  errors: ImportError[]
  duration: number
  details: ImportResultDetail[]
}

export interface ImportResultDetail {
  entity: string
  action: "inserted" | "updated" | "skipped" | "error"
  identifier: string
  error?: string
}

// ============ WIZARD STATE ============

export interface ImportWizardState {
  importType: ImportType | null
  file: ParsedFile | null
  selectedSheet: string | null
  mappings: ColumnMapping[]
  validation: ValidationResult | null
  editedRows: Map<number, Record<string, unknown>>
  progress: ImportProgress
  savedMappings: MappingTemplate[]
}
